import org.gradle.api.tasks.testing.logging.TestLogEvent

plugins {
    id 'java'
//    id 'org.jetbrains.kotlin.jvm' version "1.6.0"
    id 'org.jetbrains.intellij' version '1.4.0'
}

def properties(String key) { providers.gradleProperty(key) }
def environment(String key) { providers.environmentVariable(key) }

group = libs.versions.pluginGroup.get()
version = libs.versions.pluginVersion.get()

repositories {
    mavenLocal()
    maven { url uri('local-repo') }
    maven { url 'https://nexus-internal.headoffice.psbank.local/repository/at-maven-group/' }
    maven { url 'https://nexus-external/repository/deprecated-repo.haulmont.com-proxy' }
    maven { url 'https://nexus-external/repository/maven-public/' }
    maven { url 'https://nexus-external/repository/maven-newathena-proxy' }
    maven { url 'https://nexus-external/repository/repo1.maven.org-proxy/' }
}

dependencies {
    implementation(libs.jakarta)
    implementation(libs.jsoup)
    implementation(libs.slf4j)
    implementation(libs.testit.api)
    implementation 'ru.psb.testit:testit-java-commons:1.2.8'
    implementation 'com.squareup.okhttp3:okhttp:3.9.1'
    compileOnly fileTree(dir: "${projectDir}/idea-IC-241.17890.1/lib", include: ['*.jar'])
    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.2'
    implementation "org.projectlombok:lombok:1.18.22"
    compileOnly "org.projectlombok:lombok:1.18.22"
    annotationProcessor "org.projectlombok:lombok:1.18.22"
    testAnnotationProcessor "org.projectlombok:lombok:1.18.22"
}

intellij {
//    version = libs.versions.ideaVersion.get()
//    localPath = "${projectDir}/idea-IC-241.17890.1/"
    localPath = "/home/opt/intllijidea/idea-IC-241.17890.1/"
    type = 'IC'
    plugins = ['java']
}

buildSearchableOptions {
    enabled = false
}

instrumentCode {
    enabled = true
}

instrumentTestCode {
    enabled = false
}

patchPluginXml {
    sinceBuild = libs.versions.pluginSinceBuild
    untilBuild = libs.versions.pluginUntilBuild
}

publishPlugin {
    token = environment('PUBLISH_TOKEN')
}

signPlugin {
    certificateChain = environment('CERTIFICATE_CHAIN')
    privateKey = environment('PRIVATE_KEY')
    password = environment('PRIVATE_KEY_PASSWORD')
}

tasks.withType(JavaCompile).configureEach {
    sourceCompatibility = libs.versions.javaVersion.get()
    targetCompatibility = libs.versions.javaVersion.get()
    options.incremental = true
    options.fork = true
    options.encoding = libs.versions.javaEncoding.get()
}

tasks.withType(Test).configureEach {
    def logPropsFile = sourceSets.main.resources.find {
        it.name.endsWith('logging.properties')
    }

    if (logPropsFile?.exists()) {
        systemProperty 'java.util.logging.config.file', logPropsFile
    }

    systemProperty 'java.util.logging.manager', 'java.util.logging.LogManager'
    systemProperty 'TEST_CI', System.getProperty('testCi')

    reports {
        html.required = true
        junitXml.required = false
    }
    testLogging {
        events = [TestLogEvent.FAILED, TestLogEvent.PASSED, TestLogEvent.SKIPPED] as Set
        showCauses = false
        showStackTraces = false
        showStandardStreams = true
    }
    outputs.upToDateWhen { false }
    useJUnitPlatform()
}
