pluginRepositoryUrl=https://github.com/testit-tms/testit-management/
mvnProxyUrl=https://nexus-external/repository/maven-public/
platformType=IC
platformPlugins=
platformBundledPlugins=
kotlin.code.style=official
kotlin.stdlib.default.dependency=false
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=true
org.gradle.parallel=true
org.gradle.warning.mode=all
org.gradle.welcome=never
org.gradle.jvmargs=-XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC

systemProp.javax.net.ssl.trustStore=./jssecacerts
